[package]
name = "sidecar"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
nix = { version = "0.30.1", features = ["process", "signal"] }

env_logger = "0"
log = "0.4.28"
thiserror = "2"
futures = "0.3.31"

#agones = "1.53"

[dev-dependencies]
rand = "0.10.0-rc.5"
itertools = "0.14.0"